export default function AiInsight({ text, className = "" }) {
  if (!text) return null

  return (
    <div className={className}>
      {text.split("\n\n").map((paragraph, i) => (
        <p key={i} className="text-caption text-gray-600 mb-1.5 last:mb-0">{paragraph}</p>
      ))}
      <p className="text-caption italic text-gray-400 mt-1.5">Generated by Claude AI</p>
    </div>
  )
}
