import { useState } from "react"
import PowerRankingRow from "./PowerRankingRow"

const TABS = [
  { key: "next_week", label: "Next week" },
  { key: "rest_of_season", label: "Rest of season" },
]

export default function PowerRankingList({ nextWeek, restOfSeason, houseguestsById }) {
  const [tab, setTab] = useState("next_week")
  const list = tab === "next_week" ? nextWeek : restOfSeason

  return (
    <div>
      <div className="flex gap-2 px-4 pt-2 pb-3">
        {TABS.map(t => (
          <button
            key={t.key}
            onClick={() => setTab(t.key)}
            className={`flex-1 rounded-pill px-3 py-1.5 text-caption font-semibold transition-colors ${
              tab === t.key ? "bg-gray-900 text-white" : "bg-gray-100 text-gray-500"
            }`}
          >
            {t.label}
          </button>
        ))}
      </div>

      {list.length === 0 ? (
        <p className="text-caption text-gray-400 text-center px-4 py-6">Nothing to show yet.</p>
      ) : (
        <div className="mx-4 bg-white rounded-card border border-gray-100 overflow-hidden">
          {list.map((entry, i) => (
            <PowerRankingRow
              key={entry.houseguest_id}
              rank={i + 1}
              houseguest={houseguestsById[entry.houseguest_id]}
              predictedPoints={entry.predicted_points}
              reason={entry.reason}
            />
          ))}
        </div>
      )}

      <p className="text-caption italic text-gray-400 text-center mt-3">Generated by Claude AI</p>
    </div>
  )
}
